// generated by `crow doc`
include ../pug-include/documentation.pug
+documentationPage("exceptions")
	section
		+record("exception", [], [["message", "arr char"], ["backtrace", "backtrace"]])
		+record("exception-ctx", [], [["jmp-buf-ptr", "ptr jmp-buf-tag", "mut"], ["thrown-exception", "exception", "mut"]])
		+function("exception-ctx", [], "by-val exception-ctx", [])
		+function("finally", ["?t"], "?t", [["after", "fun-act0 void"], ["try", "fun-act0 ?t"]])
		+function("rethrow", ["?t"], "?t", [["e", "exception"]])
		+function("throw", ["?t"], "?t", [["e", "exception"]])
		+function("assert", [], "void", [["condition", "bool"]])
		+function("assert", [], "void", [["condition", "bool"], ["message", "arr char"]])
		+function("assert", [], "void", [["condition", "bool"], ["message", "fun0 arr char"]])
		+function("fail", ["?t"], "?t", [["reason", "arr char"]])
		+function("catch", ["?t"], "result<?t, exception>", [["try", "fun-act0 ?t"]])
		+function("catch", ["?t"], "?t", [["try", "fun-act0 ?t"], ["catcher", "fun-act1<?t, exception>"]])
		+function("unreachable", ["?t"], "?t", [])
		+function("forbid", [], "void", [["condition", "bool"]])
		+function("forbid", [], "void", [["condition", "bool"], ["message", "arr char"]])
		+function("catch-with-exception-ctx", ["?t"], "?t", [["ec", "exception-ctx"], ["try", "fun-act0 ?t"], ["catcher", "fun-act1<?t, exception>"]])
		+function("get-exception-ctx", [], "exception-ctx", [])
