uncaught exception: FOO
	at bar
	at foo
	at main_0
	at add__sfirst__stask__lambda0
	at call__sw__sctx_586
	at catch_0__lambda0
	at call__sw__sctx_583
	at catch_1
	at catch_0
	at subscript_19__lambda0
	at call__sw__sctx_1120
	at invoke__saction
	at do__stask
	at thread__sfunction
	at thread__sfun
	at pthread_condattr_setpshared
