exit code: 1
stderr:
uncaught exception: FOO
	at bar
	at foo
	at main
	at add
	at call
	at then
	at call
	at catch
	at call
	at catch
	at catch
	at then
	at call
	at invoke
	at do
	at thread
