uncaught exception: FOO
	at bar
	at foo
	at main_0
	at add__sfirst__stask__lambda0
	at call__sw__sctx_477
	at catch_0__lambda0
	at call__sw__sctx_474
	at catch_1
