uncaught exception: FOO
	at get-backtrace
	at throw
	at bar
	at foo
	at main
	at *
	at call-with-ctx
	at subscript
