uncaught exception: FOO
	at get-backtrace
	at fail<void>
	at bar
	at foo
	at main
	at add-first-task.lambda0
	at 
	at subscript<fut<?r>>
